---
title: "Scratch Work"
author: "Brianna Cirillo"
output: html_notebook
---

```{r}
EcologyBias <- EcologyBias_Daneshgar_Popo_2_[1:175, ]
library(dplyr)
library(mosaic)
library(mosaicCore)
```

```{r}
# This is just a nice way to print results
# cat('What you want the print out to say' , code you want to run, '\n')

#This is doing counts for Marine, Terrestrial, Freshwater, Mixed
cat('Number of Journal Entries in Marine: ' , count(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed` == "Marine"), '\n')
cat('Number of Journal Entries in Terrestrial: ' , count(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed` == "Terrestrial"), '\n')
cat('Number of Journal Entries in Freshwater: ' , count(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed` == "Freshwater"), '\n')
cat('Number of Journal Entries in Mixed: ' , count(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed` == "Mixed"), '\n')
```

```{r}
#This is doing counts for Region

cat('Number of Journal Enties by Region:' , '\n', '\n')
cat('Number of Journal Entries in East-North Central: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "East-North Central"), '\n')
cat('Number of Journal Entries in Mid-Atlantic: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "Mid-Atlantic"), '\n')
cat('Number of Journal Entries in Mid-South: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "MidSouth"), '\n')
cat('Number of Journal Entries in Mountain: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "Mountain"), '\n')
cat('Number of Journal Entries in New England: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "New England"), '\n')
cat('Number of Journal Entries in North West: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "NW"), '\n')
cat('Number of Journal Entries in Pacific: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "Pacific"), '\n')
cat('Number of Journal Entries in South Atlantic: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "South Atlantic"), '\n')
cat('Number of Journal Entries in West North Central: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "West North Central"), '\n')
cat('Number of Journal Entries in West South Central: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "West South Central"), '\n')
cat('Number of Journal Entries in META ANALYSIS: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "META ANALYSIS"), '\n')
cat('Number of Journal Entries in Multiple: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "Multiple"), '\n')
cat('Number of Journal Entries in Multiple Ranges: ' , count(EcologyBias$`Regions where the work was done  (Popo defines)` == "Multiple Ranges"), '\n')
```


```{r}
#This is doing counts for Ecosystem

cat('Number of Journal Enties by Ecosystem:' , '\n', '\n')
cat('Number of Journal Entries in Coastal Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Coastal Ecosystems"), '\n')
cat('Number of Journal Entries in Coniferous Forestss: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Coniferous Forests"), '\n')
cat('Number of Journal Entries in Deciduous and Evergreens: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Deciduous and Evergreen"), '\n')
cat('Number of Journal Entries in Ecosystems of the Deep Ocean: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Ecosystems of the Deep Ocean"), '\n')
cat('Number of Journal Entries in Inland Aquatic Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Inland Aquatic Ecosystems"), '\n')
cat('Number of Journal Entries in CLakes and Reservoirs Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Lakes and Reservoirs Ecosystems"), '\n')
cat('Number of Journal Entries in Managed Terrestrial Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Managed Terrestrial Ecosystems"), '\n')
cat('Number of Journal Entries in Polar & Alpine Tundra: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Polar & Alpine Tundra"), '\n')
cat('Number of Journal Entries in Shrublands: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Shrublands"), '\n')
cat('Number of Journal Entries in Temperate Deciduous Forests: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Temperate Deciduous Forests"), '\n')
cat('Number of Journal Entries in Tropical Forests: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Tropical Forests"), '\n')
cat('Number of Journal Entries in CWetland Forests: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Wetland Forests"), '\n')
cat('Number of Journal Entries in Coniferous and Hardwood: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Coniferous and Hardwood"), '\n')
cat('Number of Journal Entries in Coral Reefs: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Coral Reefs"), '\n')
cat('Number of Journal Entries in Ecosystems of the Continental Shelves: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Ecosystems of the Continental Shelves"), '\n')
cat('Number of Journal Entries in Estuaries and Enclosed Seas: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Estuaries and Enclosed Seas"), '\n')
cat('Number of Journal Entries in Intertidal and Littoral Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Intertidal and Littoral Ecosystems"), '\n')
cat('Number of Journal Entries in Managed Aquatic Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Managed Aquatic Ecosystems"), '\n')
cat('Number of Journal Entries in Natural Grasslands: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Natural Grasslands"), '\n')
cat('Number of Journal Entries in River and Stream Ecosystem: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "River and Stream Ecosystem"), '\n')
cat('Number of Journal Entries in Temperate Broad Leaved Evergreen: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Temperate Broad Leaved Evergreen"), '\n')
cat('Number of Journal Entries in Temperate Deserts and Semi Deserts: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Temperate Deserts and Semi Deserts"), '\n')
cat('Number of Journal Entries in Tropical Savannas: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "CTropical Savannas"), '\n')
cat('Number of Journal Entries in Multiple Ecosystems: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "Multiple"), '\n')
cat('Number of Journal Entries in META-ANALYSIS: ' , count(EcologyBias$`Ecosystem (Ped defines)` == "META-ANALYSIS"), '\n')
```

```{r}
#This is doing counts for Phylum

cat('Number of Journal Enties by Phylum:' , '\n', '\n')
cat('Number of Journal Entries in Annelida: ' , count(EcologyBias$Phylum == "Annelida"), '\n')
cat('Number of Journal Entries in Anthophyta: ' , count(EcologyBias$Phylum == "Anthophyta"), '\n')
cat('Number of Journal Entries in Arthropoda: ' , count(EcologyBias$Phylum == "Arthropoda"), '\n')
cat('Number of Journal Entries in Chordata: ' , count(EcologyBias$Phylum == "Chordata"), '\n')
cat('Number of Journal Entries in Cnidaria: ' , count(EcologyBias$Phylum == "Cnidaria"), '\n')
cat('Number of Journal Entries in Coniferophyta: ' , count(EcologyBias$Phylum == "Coniferophyta"), '\n')
cat('Number of Journal Entries in Echinodermata: ' , count(EcologyBias$Phylum == "Echinodermata"), '\n')
cat('Number of Journal Entries in Magnoliophyta: ' , count(EcologyBias$Phylum == "Magnoliophyta"), '\n')
cat('Number of Journal Entries in Mollusca: ' , count(EcologyBias$Phylum == "Mollusca"), '\n')
cat('Number of Journal Entries in Ochrophyta: ' , count(EcologyBias$Phylum == "Ochrophyta"), '\n')
cat('Number of Journal Entries in Oomycota: ' , count(EcologyBias$Phylum == "Oomycota"), '\n')
cat('Number of Journal Entries in Spermatophyta: ' , count(EcologyBias$Phylum == "Spermatophyta"), '\n')
cat('Number of Journal Entries in Tracheophyta: ' , count(EcologyBias$Phylum == "Tracheophyta"), '\n')
cat('Number of Journal Entries in Multiple: ' , count(EcologyBias$Phylum == "Multiple"), '\n')
```

```{r}
#if (EcologyBias$Phylum == "Spermatophyta"){
  #count(EcologyBias$`Genus (only if single species)`)
#}

#with(EcologyBias$`Genus (only if single species)`, ftable(EcologyBias$Phylum =="Spermatophyta"))

#cat('Number of Journal Enties by Phylum & Genus:' , '\n', '\n')
```


```{r}
# Making a contingency table using the tally function 
# Region

# Makes the data into a vector
region <- as.vector(EcologyBias$`Regions where the work was done  (Popo defines)`)

# Removes the NAs from the vector
region <- region[!is.na(region)]

# Making the contingency table of the data without NAs
tally(region)
```

```{r}
# Making a contingency table using the tally function 
# Marine, terrestrial, freshwater, mixed
tally(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed`)
```

```{r}
# Making a contingency table using the tally function 
# Ecosystem
tally(EcologyBias$`Ecosystem (Ped defines)`)
```


```{r}
# Making a contingency table using the tally function 
# Phylum
tally(EcologyBias$Phylum)
```

```{r}
# Making a contingency table using the tally function 
# Genus
tally(EcologyBias$`Genus (only if single species)`)
```

# Attempting to rename columns, didn't work

```{r}
EcologyBias %>%
  rename(Genus = "Genus (only if single species)")
```


# Removing Mult data for more Accurate Chi-Square

```{r}
# Looking at the contingency tables to see which have multiples so we can remove them

tally(EcologyBias$`Country where the work is done`) # needs to be fixed
tally(EcologyBias$`Regions where the work was done  (Popo defines)`) # needs to be fixed
tally(EcologyBias$`State or Municipality where the work was done`) # needs to be fixed
tally(EcologyBias$`Continent where work done`) # needs to be fixed

```

## Continent

```{r}
continent.work <- as.vector(EcologyBias$`Continent where work done`)
remove <- c ("Europe & Oceania", "META ANALYSIS","META ANALYSIS!")
continent.work %in% remove
continent.work <- continent.work [! continent.work %in% remove]
continent.work[43] <- "Oceania"
continent.work[61] <- "Oceania"
continent.work <- c(continent.work[1:97], continent.work[99:168])
continent.work
continent <- as.matrix(table(continent.work))
xchisq.test(tally(continent.work))

```


## Country

```{r}
# Running Chi-Sq After removing Multiples

# Making the column for country into a vector
country.work <- as.vector(EcologyBias$`Country where the work is done`)

# Printing the vector to look for the multiples we need to remove
country.work

# Creating a vector of the data names of what we need to remove
remove <- c ("US and Mexico","Multiple???", "META ANALYSIS")

# %in% returns a boolean TRUE if it is in remove, false if not
country.work %in% remove

# Removing everything in the remove vector from country.work
country.work <- country.work [! country.work %in% remove]

#Printing the vector to make sure we didn't miss anything
country.work

# This is changing 1-5 and 8-11 from US to USA so everything matches
country.work[1:5] <- "USA"
country.work[8:11] <- "USA"

# Printing the vector to make sure it worked properly
country.work

# Removing any NA
country.work <- country.work[!is.na(country.work)]

# Printing the vector to make sure it worked properly
country.work

# Rerunning the contingency table to to look at the new counts
tally(country.work)

# Running the chi-squared on the new data
chisq.test(tally(country.work))

```

## Region

```{r}
# The code is doing the exact same thing as in the chunk above

region.work <- as.vector(EcologyBias$`Regions where the work was done  (Popo defines)`)

region.work

remove <- c ("Multiple", "META ANALYSIS", "Multiple Ranges")

region.work %in% remove

region.work <- region.work [! region.work %in% remove]

region.work

region.work <- region.work[!is.na(region.work)]

region.work

tally(region.work)

chisq.test(tally(region.work))
```



## State

```{r}
# The code is doing the exact same thing as in the chunk above

state.work <- as.vector(EcologyBias$`State or Municipality where the work was done`)


remove <- c ("Multiple States", "Multiple", "META ANALYSIS", "OR/CA", "GA/FL", "NY, MA, CT")

state.work %in% remove

state.work <- state.work [! state.work %in% remove]

state.work <- state.work[!is.na(state.work)]

tally(state.work)

chisq.test(tally(state.work))
```

## MTF

```{r}
# Making the column for ecosystem into a vector
ecosystem.MTF <- as.vector(EcologyBias$`Marine, Terrestrial, Freshwater, Mixed`)

# Printing the vector to look for data names we need to remove
ecosystem.MTF

# Creating a vector of the data names of what we need to remove
remove <- c ("Mixed")

# Removing everything in the remove vector from ecosystem.MTF
ecosystem.MTF %in% remove
ecosystem.MTF <- ecosystem.MTF [! ecosystem.MTF %in% remove]

# Removing any NA
ecosystem.MTF <- ecosystem.MTF [!is.na(ecosystem.MTF)]

# Rerunning the contingency table to to look at the new counts
tally(ecosystem.MTF)

# Running the chi-squared on the new data
chisq.test(tally(ecosystem.MTF))
```

```{r}
EcologyBias2 <- EcologyBias_Daneshgar_Popo_2_2

ecosystems <- matrix(c(EcologyBias2$`Marine, Terrestrial, Freshwater, Mixed`, EcologyBias2$`Ecosystem (Ped defines)`), ncol=2)

ecosystems <- ecosystems [!is.na(ecosystems)]

ecosystems

#ecosystems
eco.t <- vector()
eco.m <- vector()
eco.f <- vector()

for(i in 1:317){
if(ecosystems[i,1]=="Terrestrial"){
  eco.t[i] <- ecosystems[i,2]
}
if(ecosystems[i,1]=="Marine"){
  eco.m[i] <- ecosystems[i,2]
}else{
  eco.f[i] <- ecosystems[i,2]
}}

tally(eco.t)
tally(eco.m)
tally(eco.f)
```


## Possible fixes

Look at multiple journals that are located in different regions around the 

