---
title: "Odalys Personal Reflection"
output: html_notebook
---
This semester has taught me a lot about applying my statistical knowledge. In most statistics classes we are what taught about statistics but this class really dives deep into applying the material. I learned how to answer my clients and my own questions without going to the professor first. From the beginning, my group had a hard time planning what we were going to do for our client. We understood what our client's goals were, but we had no idea how to get there. This semester has taught me to think outside the box. I learned how to communicate not only with my group members, but also with my client. Since we did not have the right data to answer his research question, we had to have a serious talk and tell him that we weren't going to be able to answer his original question. He was very nice and understanding which made the process stress free. Because of my clients project, I learned about ecosystems and why certain areas of the world are more popular for ecology work. I learned that publications bias exists but statistically proving bias exists is very difficult. In fact, it may be impossible to prove this without having the right data. We tried our best to see if there were alternative questions to answer but in the end none of these approaches would answer our clients true question. 

I am surprised at how much we were able to do. At first I wasn't sure if we were going to have a project since we couldn't answer his question but we found our way around those problems. I think this project will help Christiana analyze her data for her Honors Thesis. She now knows the obstacles she will face before she starts running the same test we did. I think we left her a the right track and maybe this will lead to new ideas that our group didn't think of. 

Because of this class I know I am on the right path. I enjoy what I am doing and what I am learning about. I think I work well as a group and individually. I think I am very understanding of others and I just go with the flow. I like structure and I like having a plan but, I also understand that things will not always go according to planned. This is okay, there is no need to stress to much about it. Because of this class, my self confidence especially when it comes to presenting has improved. I still don't think I am a pro but with practice I will get better. I think this class was fun. I have learned a lot and I have no complaints. 

