---
title: "Veronica's Personal Reflection"
output: html_notebook
---



This semester wasn't what I was expecting at all, I came into the class doubting my own abilities. I learned that Statistics goes beyond just text book work and manual calculations. I got the chance to be exposed to a "professional" setting, I was apart of a team, we had a client. We discussed their plans and soon realized those plans may not be met to what the client believed. We as a team found ways to ask questions and analyze the data we were giving. We maneuvered our way through the data and our own knowledge to find the best possible approach. But at some point we as a team had to tell the client the hard truth of what we were up against. Tell the client the approach we could do for him that could benefit his wishes without changing every piece of information he provided us. Communication with not just the client, but with my group was something that we could agree we excelled in. We knew when we needed to tell each other something was not working and we had to find a new "path". Even with the client knowing the hard truth, he was very cooperative with that truth. Which made it a bit more stress relieving not only for myself but for the team. Throughout the whole semester I learned so much about Ecology in itself, I always had a itch for the sciences. I saw through our findings that a form of bias does exist even though statistically we couldn't prove it. We could assume just by our visuals which wasn't surprising to see because various areas have that same "bias."

After everything our group has gone through together it was amazing how we could actually analyze the data provided. Don't get me wrong it was definitely hard to do, but after reviewing and discussing we found it. It was a lesson we needed, there will never be a "right" answer the first time around. But as long as you don't give up, that "right" answer will come along the way. I believe  Christiana has all the right and useful information she needs to continue with her study. 

I personally learned how to let my mind roam free a bit more to ask different questions then I'm used to asking. Something that I'm really proud of is taking the time on my own time to go through the text and make anki cards on R commands. This helped me really understand the code we used throughout the semester. Again this was a doubt of mine, knowing little to nothing about Statistics or even R I questioned why I was even selected to be apart of such an amazing group of students. I'm the type of person to never settle for one area, because I know there is always something to learn. So, the fact that I never really took the chance to consider myself a future in Statistics was surprising. But now looking into my potential future, I could see myself pursuing a career which will involve the best of both worlds. This class was such an amazing experience and I thank my professors for the opportunity. I especially like to thank my team, Odalys and Bri really motivated me to keep pushing myself past my own limits. Even if they don't know that, they have been such a help this semester. 